name: Build
on: [ pull_request, push ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.SIGNING_KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/release_keystore.jks
          echo "${TMP_KEYSTORE_FILE_PATH}"
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Run Lint
        run: ./gradlew lint

      - name: Generate Annotation from the Lint report
      - uses: yutailang0119/action-android-lint@v3
        with:
          report-path: build/reports/*.xml
          continue-on-error: false

      - name: Build the bundle
        env:
          ANDROID_RELEASE_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          ANDROID_RELEASE_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          ANDROID_RELEASE_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          ANDROID_RELEASE_KEYSTORE: "/home/runner/work/_temp/keystore/release_keystore.jks"
        run: sh ./gradlew app:bundleRelease

      - name: Upload artifcats
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: app/build/outputs/